[package]
name = "sessions-core"
version = "0.2.3"
authors = ["FangDun Tsai <cfddream@gmail.com>"]
description = "Sessions Core"
documentation = "https://docs.rs/sessions-core"
homepage = "https://github.com/viz-rs/sessions"
license = "Apache-2.0/MIT"
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
cookie = "0.15"
serde = "1.0"
serde_json = "1.0"
