[package]
name = "sessions-sled"
version = "0.2.0"
authors = ["FangDun Tsai <cfddream@gmail.com>"]
description = "Sessions Sled Storage"
license = "Apache-2.0/MIT"
edition = "2018"
publish = false

[dependencies]
sessions-core = { path = "../sessions-core", version = "0.2.0" }

sled = "0.34"
